var CardConstants = {
  PICTURES_RECEIVED: "PICTURES_RECEIVED",
  CARDS_RECEIVED: "CARDS_RECEIVED",
  CARD_SELECTED: "CARD_SELECTED",
  UPDATED_CARD_RECEIVED: "UPDATED_CARD_RECEIVED",
  PICTURE_MATCHED: "PICTURE_MATCHED",
  CARD_ADDED: "CARD_ADDED",
  CLEAR: "CLEAR"
};

export default CardConstants
